apiVersion: operator.higress.io/v1alpha1
kind: HigressController
metadata:
  labels:
    app.kubernetes.io/name: higresscontroller
    app.kubernetes.io/instance: higresscontroller-sample
    app.kubernetes.io/part-of: higressoperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: higressoperator
  name: higress-controller
  namespace: higress-system
spec:
  ingressClass: "higress"
  meshConfig:
    trustDomain: "cluster.local"
    accessLogEncoding: "JSON"
    accessLogFile: "/dev/stdout"
    ingressControllerMode: "OFF"
    accessLogFormat: '{"authority":"%REQ(:AUTHORITY)%","bytes_received":"%BYTES_RECEIVED%","bytes_sent":"%BYTES_SENT%","downstream_local_address":"%DOWNSTREAM_LOCAL_ADDRESS%","downstream_remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%","duration":"%DURATION%","istio_policy_status":"%DYNAMIC_METADATA(istio.mixer:status)%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol":"%PROTOCOL%","request_id":"%REQ(X-REQUEST-ID)%","requested_server_name":"%REQUESTED_SERVER_NAME%","response_code":"%RESPONSE_CODE%","response_flags":"%RESPONSE_FLAGS%","route_name":"%ROUTE_NAME%","start_time":"%START_TIME%","trace_id":"%REQ(X-B3-TRACEID)%","upstream_cluster":"%UPSTREAM_CLUSTER%","upstream_host":"%UPSTREAM_HOST%","upstream_local_address":"%UPSTREAM_LOCAL_ADDRESS%","upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","upstream_transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%","user_agent":"%REQ(USER-AGENT)%","x_forwarded_for":"%REQ(X-FORWARDED-FOR)%"}'
    dnsRefreshRate: 200s
    enableAutoMtls: false
    enablePrometheusMerge: true
    protocolDetectionTimeout: 100ms
    configSources:
      - address: "xds://127.0.0.1:15051"
    defaultConfig:
      disableAlpnH2: true
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*"
  enableStatus: true
  local: true
  jwtPolicy: "third-party-jwt"
  controller:
    name: "dsy-controller"
    image:
      repository: "luckymrwang/higress"
      tag: "0.0.5"
      imagePullPolicy: "IfNotPresent"
    gatewayName: "higress-gateway"
    sdsTokenAud: "istio-ca"
  console:
    selectorLabels:
      app: console
    service:
      type: NodePort
      ports:
      - name: http
        nodePort: 30083
        port: 8080
        protocol: TCP
        targetPort: http
    configMapSpec:
      chat.enabled: false
      chat.endpoint: ""
      scope: dd
      system.initialized: true
    name: "dsy-console"
    image:
      repository: "luckymrwang/higress-console"
      tag: "0.1.5"
      imagePullPolicy: "IfNotPresent"
    env:
      JAVA_HOME: "/usr/local/openjdk-18"
      LANG: "C.UTF-8"
      HIGRESS_CONSOLE_NS: "higress-system"
      HIGRESS_CONSOLE_ADMIN_SECRET: "higress-console"
      HIGRESS_CONSOLE_CONFIG_MAP_NAME: "higress-console"
      HIGRESS_CONSOLE_CONTROLLER_JWT_POLICY: "third-party-jwt"
      HIGRESS_CONSOLE_DASHBOARD_BASE_URL: "http://higress-console-grafana.higress-system:3000/grafana"
      HIGRESS_CONSOLE_DASHBOARD_DATASOURCE_URL: "http://higress-console-prometheus.higress-system:9090/prometheus"
      HIGRESS_CONSOLE_CONTROLLER_INGRESS_CLASS_NAME: "higress"
  pilot:
    name: "pilot"
    image:
      repository: "luckymrwang/pilot"
      tag: "0.0.5"
      imagePullPolicy: "IfNotPresent"
    env:
      PILOT_SCOPE_GATEWAY_TO_NAMESPACE: "false"
      PILOT_ENABLE_METADATA_EXCHANGE: "false"
      PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: "false"
      VALIDATION_ENABLED: "false"
      PILOT_ENABLE_GATEWAY_API: "true"
      PILOT_ENABLE_GATEWAY_API_STATUS: "true"
      PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "false"
    traceSampling: "1.0"
    keepaliveMaxServerConnectionAge: 30m
    clusterDomain: "cluster.local"
    oneNamespace: false
    enableProtocolSniffingForOutbound: true
    enableProtocolSniffingForInbound: true
